# Generated by Django 5.0.7 on 2024-07-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0007_video_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo_profil_copyright',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos')),
                ('copyright', models.CharField(max_length=4)),
            ],
        ),
    ]
