# Generated by Django 5.0.7 on 2024-07-23 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0008_photo_profil_copyright'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo_profil_copyright',
            new_name='Photo_profil_cop',
        ),
    ]
