# Generated by Django 5.0.7 on 2024-07-23 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0009_rename_photo_profil_copyright_photo_profil_cop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo_profil_cop',
        ),
    ]
