# Generated by Django 5.0.7 on 2024-08-11 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0011_commentaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='about_body',
        ),
        migrations.DeleteModel(
            name='Commentaire',
        ),
    ]
