# Generated by Django 5.0.7 on 2024-08-11 17:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0012_remove_about_about_body_delete_commentaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='about_body',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
