# Generated by Django 5.0.7 on 2024-08-11 17:30

import froala_editor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0013_about_about_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_body',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
