# Generated by Django 5.0.7 on 2024-08-11 17:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0014_alter_about_about_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='sub_about_body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
